# Generated by Django 5.1.2 on 2025-05-26 11:16

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("deck", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="", null=True)),
                ("birthday", models.TextField(blank=True, null=True)),
                ("friends", models.TextField(blank=True, null=True)),
                ("enemies", models.TextField(blank=True, null=True)),
                ("games", models.TextField(blank=True, null=True)),
                ("first_game", models.CharField(max_length=50)),
                ("franchises", models.TextField(blank=True, null=True)),
                ("image", models.TextField(blank=True, null=True)),
                ("images", models.TextField(blank=True, null=True)),
                ("character_id", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "db_table": "Characters",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_id", models.CharField(max_length=255, unique=True)),
                ("game_name", models.CharField(max_length=255)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("retail_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("thumb_url", models.CharField(max_length=255)),
                ("store_name", models.CharField(max_length=255)),
                ("store_icon_url", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Deals",
            },
        ),
        migrations.CreateModel(
            name="Franchise",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                ("games", models.CharField(max_length=200)),
                ("image", models.TextField(blank=True, null=True)),
                ("images", models.TextField(blank=True, null=True)),
                ("games_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "Franchises",
                "ordering": ["title", "games_count"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("guid", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("overview", models.TextField(blank=True, null=True)),
                ("genres", models.CharField(max_length=200)),
                ("platforms", models.CharField(max_length=200)),
                ("themes", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.TextField()),
                (
                    "release_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("developers", models.CharField(blank=True, max_length=100, null=True)),
                ("game_images", models.TextField(blank=True, null=True)),
                (
                    "similar_games",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("dlcs", models.CharField(blank=True, max_length=200, null=True)),
                ("franchises", models.CharField(blank=True, max_length=200, null=True)),
                ("videos", models.TextField()),
                ("concepts", models.CharField(max_length=200)),
                ("is_casual", models.BooleanField(default=False)),
                ("is_popular", models.BooleanField(default=False)),
                ("playtime", models.CharField(blank=True, max_length=100, null=True)),
                ("pc_req_min", models.TextField(blank=True, null=True)),
                ("pc_req_rec", models.TextField(blank=True, null=True)),
                ("mac_req_min", models.TextField(blank=True, null=True)),
                ("mac_req_rec", models.TextField(blank=True, null=True)),
                ("linux_req_min", models.TextField(blank=True, null=True)),
                ("linux_req_rec", models.TextField(blank=True, null=True)),
                ("average_score", models.FloatField(blank=True, null=True)),
                ("total_reviews", models.IntegerField(blank=True, null=True)),
                ("translated_description_ro", models.TextField(blank=True, null=True)),
                ("translated_overview_ro", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Games",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="GameModes",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("game_id", models.CharField(max_length=100)),
                ("game_name", models.CharField(max_length=100)),
                ("game_mode", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "GameModes",
            },
        ),
        migrations.CreateModel(
            name="GameStores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("store_name", models.CharField(blank=True, max_length=255, null=True)),
                ("store_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "GameStores",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "article_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "publish_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("platforms", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "News",
            },
        ),
        migrations.CreateModel(
            name="GameList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("game_guids", models.JSONField(default=list)),
                ("additional_games", models.CharField(blank=True, max_length=1000)),
                ("shared_by", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_game_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_game_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_game_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Comment")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="playstyle_compass.gamelist",
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "List Comment",
                "verbose_name_plural": "List Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("shared_by", models.JSONField(blank=True, default=dict)),
                ("duration", models.DurationField(default=datetime.timedelta(days=7))),
                ("is_public", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=120)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="playstyle_compass.poll",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewers", models.CharField(max_length=25)),
                ("review_deck", models.CharField(max_length=50)),
                ("review_description", models.TextField()),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("likes", models.IntegerField(blank=True, default=0, null=True)),
                ("dislikes", models.IntegerField(blank=True, default=0, null=True)),
                ("liked_by", models.TextField(blank=True, null=True)),
                ("disliked_by", models.TextField(blank=True, null=True)),
                (
                    "date_added",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playstyle_compass.game",
                        to_field="guid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="SharedGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_deleted_by_sender", models.BooleanField(default=False)),
                ("is_deleted_by_receiver", models.BooleanField(default=False)),
                ("game_id", models.BigIntegerField()),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Message",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("gaming_history", models.TextField(blank=True)),
                ("favorite_genres", models.CharField(blank=True, max_length=255)),
                ("platforms", models.CharField(blank=True, max_length=255)),
                ("themes", models.CharField(blank=True, max_length=255)),
                ("quiz_recommendations", models.CharField(blank=True, max_length=255)),
                ("connection_types", models.CharField(blank=True, max_length=255)),
                ("game_styles", models.CharField(blank=True, max_length=255)),
                ("show_in_queue", models.BooleanField(default=True)),
                ("show_reviews", models.BooleanField(default=True)),
                ("show_favorites", models.BooleanField(default=True)),
                (
                    "favorite_games",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_by_users",
                        to="playstyle_compass.game",
                    ),
                ),
                (
                    "game_queue",
                    models.ManyToManyField(
                        blank=True,
                        related_name="queued_by_users",
                        to="playstyle_compass.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating between 1 (worst) and 5 (best)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="playstyle_compass.gamelist",
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("game_list", "user")},
            },
        ),
        migrations.CreateModel(
            name="SharedDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playstyle_compass.deal",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "SharedDeals",
                "unique_together": {("sender", "recipient", "deal")},
            },
        ),
        migrations.CreateModel(
            name="SharedReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_review_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playstyle_compass.review",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_review_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("sender", "recipient", "review")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="playstyle_compass.polloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="playstyle_compass.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("poll", "user")},
            },
        ),
    ]
