# Generated by Django 5.1.2 on 2024-12-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="playtime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
