# Generated by Django 4.2.4 on 2023-08-19 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0002_game_remove_userpreferences_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
    ]
