# Generated by Django 5.1.2 on 2025-01-09 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0002_poll_liked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="shared_by",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="poll",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_polls", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
