# Generated by Django 4.2.4 on 2024-01-06 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playstyle_compass", "0002_alter_review_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Message",
            new_name="SharedGame",
        ),
        migrations.AddField(
            model_name="game",
            name="dlcs",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
