# Generated by Django 4.2.4 on 2023-08-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0003_delete_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("genres", models.CharField(max_length=200)),
                ("platforms", models.CharField(max_length=200)),
                ("themes", models.CharField(max_length=200)),
            ],
        ),
    ]
