# Generated by Django 4.2.4 on 2024-01-06 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playstyle_compass", "0003_rename_message_sharedgame_game_dlcs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedgame",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sharedgame",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
