# Generated by Django 5.1.2 on 2025-01-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0003_poll_shared_by_poll_shared_with"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
