# Generated by Django 4.2.4 on 2023-08-19 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0004_game"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="game",
            table="Games",
        ),
    ]
