# Generated by Django 5.1.2 on 2025-01-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0004_alter_poll_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
