# Generated by Django 5.1.2 on 2025-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0005_alter_poll_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="description",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
