# Generated by Django 4.2.4 on 2024-01-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0006_remove_sharedgame_game_sharedgame_game_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="franchise",
            field=models.CharField(default="N/a", max_length=200),
            preserve_default=False,
        ),
    ]
