# Generated by Django 5.1.2 on 2025-01-28 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0006_alter_poll_description_alter_poll_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
