# Generated by Django 4.2.4 on 2023-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0006_alter_game_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
