# Generated by Django 4.2.4 on 2023-08-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0007_game_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="release_date",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
