# Generated by Django 5.1.2 on 2025-02-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0007_poll_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
