# Generated by Django 4.2.4 on 2024-02-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0008_franchise_rename_franchise_game_franchises"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="franchise",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="franchise",
            name="games_count",
            field=models.IntegerField(default=0),
        ),
    ]
