# Generated by Django 4.2.4 on 2023-09-11 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0008_game_release_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["title"]},
        ),
    ]
