# Generated by Django 4.2.4 on 2024-02-02 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0009_alter_franchise_options_franchise_games_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="franchise",
            options={"ordering": ["title", "games_count"]},
        ),
    ]
