# Generated by Django 5.1.2 on 2025-03-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0009_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="retail_price",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deal",
            name="sale_price",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deal",
            name="store_icon_url",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="deal",
            name="thumb_url",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="deal",
            table="Deals",
        ),
    ]
