# Generated by Django 4.2.4 on 2023-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0009_alter_game_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="overview",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.TextField(),
        ),
    ]
