# Generated by Django 5.1.2 on 2025-04-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "playstyle_compass",
            "0010_alter_deal_retail_price_alter_deal_sale_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="retail_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="deal",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
