# Generated by Django 4.2.4 on 2023-09-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0011_game_developers_alter_game_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_images",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
