# Generated by Django 5.0.1 on 2024-02-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0011_character_franchise_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="videos",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="themes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
