# Generated by Django 5.0.2 on 2024-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0013_game_guid_alter_review_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameModes",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("game_id", models.CharField(max_length=100)),
                ("game_name", models.CharField(max_length=100)),
                ("game_mode", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "GameModes",
            },
        ),
    ]
