# Generated by Django 5.0.2 on 2024-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0015_game_concepts"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="quiz_recommendations",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
