# Generated by Django 5.0.2 on 2024-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0016_userpreferences_quiz_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="linux_req_min",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="linux_req_rec",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="mac_req_min",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="mac_req_rec",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="pc_req_min",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="pc_req_rec",
            field=models.TextField(default=""),
        ),
    ]
