# Generated by Django 5.0.2 on 2024-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0017_game_linux_req_min_game_linux_req_rec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="average_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="total_reviews",
            field=models.IntegerField(default=0),
        ),
    ]
