# Generated by Django 4.2.4 on 2023-10-13 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0017_alter_game_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="game",
            table="Games",
        ),
    ]
