# Generated by Django 4.2.4 on 2023-10-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0018_alter_game_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(),
        ),
    ]
