# Generated by Django 5.0.2 on 2024-07-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0018_game_average_score_game_total_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("article_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("url", models.URLField()),
                ("image", models.URLField()),
                ("publish_date", models.CharField(max_length=50)),
                ("platforms", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "News",
            },
        ),
    ]
