# Generated by Django 5.0.2 on 2024-09-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0019_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="translated_description_ro",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="translated_overview_ro",
            field=models.TextField(blank=True, null=True),
        ),
    ]
