# Generated by Django 5.0.2 on 2024-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0020_game_translated_description_ro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="connection_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="game_style",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
