# Generated by Django 4.2.4 on 2023-10-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0021_userpreferences_favorite_games"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="favorite_games",
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="favorite_games",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
