# Generated by Django 4.2.4 on 2023-10-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0022_remove_userpreferences_favorite_games_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="similar_games",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
