# Generated by Django 4.2.4 on 2023-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0023_game_similar_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="upcoming_games",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
