# Generated by Django 4.2.4 on 2023-10-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0024_userpreferences_upcoming_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="review_deck",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="review_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="reviewers",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="score",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
