# Generated by Django 5.1.2 on 2024-10-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0025_remove_gamelist_games_gamelist_game_guids"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="additional_games",
            field=models.JSONField(default=list),
        ),
    ]
