# Generated by Django 4.2.4 on 2023-10-30 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0025_game_review_deck_game_review_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[],
            options={
                "db_table": "Games",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("playstyle_compass.game",),
        ),
    ]
