# Generated by Django 4.2.4 on 2023-10-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0026_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewers", models.CharField(max_length=25)),
                ("review_deck", models.CharField(max_length=50)),
                ("review_description", models.TextField()),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playstyle_compass.game",
                    ),
                ),
            ],
        ),
    ]
