# Generated by Django 5.1.2 on 2024-10-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0027_rename_shared_with_gamelist_shared_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamelist",
            old_name="shared_users",
            new_name="shared_with",
        ),
    ]
