# Generated by Django 4.2.4 on 2023-10-31 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0028_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
