# Generated by Django 5.1.2 on 2024-10-28 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0029_gamelist_shared_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_game_lists", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
