# Generated by Django 4.2.4 on 2023-11-01 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0030_review_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="review",
            table="Reviews",
        ),
    ]
