# Generated by Django 4.2.4 on 2023-11-07 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0031_alter_review_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="review_deck",
        ),
        migrations.RemoveField(
            model_name="game",
            name="review_description",
        ),
        migrations.RemoveField(
            model_name="game",
            name="reviewers",
        ),
        migrations.RemoveField(
            model_name="game",
            name="score",
        ),
    ]
