# Generated by Django 4.2.4 on 2023-11-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0032_remove_game_review_deck_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="upcoming_games",
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="game_queue",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
