# Generated by Django 5.1.2 on 2024-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0032_listreview_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="show_game_lists",
            field=models.BooleanField(default=True),
        ),
    ]
