# Generated by Django 4.2.4 on 2023-11-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0033_remove_userpreferences_upcoming_games_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="upcoming_games",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
