# Generated by Django 4.2.4 on 2023-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0034_userpreferences_upcoming_games"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="upcoming_games",
        ),
        migrations.AddField(
            model_name="review",
            name="dislikes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="likes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
