# Generated by Django 5.1.2 on 2024-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0035_remove_userpreferences_show_game_list_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
