# Generated by Django 4.2.4 on 2023-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0035_remove_userpreferences_upcoming_games_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
