# Generated by Django 4.2.4 on 2023-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0036_alter_review_dislikes_alter_review_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="disliked_by",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="liked_by",
            field=models.TextField(blank=True),
        ),
    ]
