# Generated by Django 5.1.2 on 2024-11-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0036_gamelist_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelist",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
