# Generated by Django 5.1.2 on 2024-11-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0037_alter_gamelist_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelist",
            name="additional_games",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
