# Generated by Django 4.2.4 on 2023-11-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "playstyle_compass",
            "0038_remove_review_disliked_by_remove_review_liked_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="disliked_by",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="liked_by",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="review",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="review",
            name="likes",
        ),
        migrations.AddField(
            model_name="review",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
