# Generated by Django 4.2.4 on 2023-11-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0039_review_disliked_by_review_liked_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="disliked_by",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="liked_by",
            field=models.TextField(blank=True, default=""),
        ),
    ]
