# Generated by Django 4.2.4 on 2023-12-15 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0040_alter_review_disliked_by_alter_review_liked_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GamingPreferences",
        ),
    ]
