# Generated by Django 5.1.2 on 2024-11-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0040_review_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="created_at",
        ),
    ]
