# Generated by Django 4.2.4 on 2023-12-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0041_delete_gamingpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="show_favorites",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="show_in_queue",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="show_reviews",
            field=models.BooleanField(default=True),
        ),
    ]
