# Generated by Django 5.1.2 on 2024-11-21 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0041_remove_review_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date_added",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
