# Generated by Django 4.2.4 on 2023-12-21 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0042_userpreferences_show_favorites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_link",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
