# Generated by Django 5.1.2 on 2024-11-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0042_review_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
