# Generated by Django 5.1.2 on 2024-11-21 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0043_alter_review_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="date_added",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
