# Generated by Django 4.2.4 on 2023-12-21 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0043_game_game_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="game_link",
        ),
    ]
