# Generated by Django 4.2.4 on 2023-12-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0045_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
