# Generated by Django 5.1.2 on 2024-11-24 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0045_listcomment_liked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelist",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_game_lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
