# Generated by Django 4.2.4 on 2023-12-21 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0046_message_content"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="message",
            table="Messages",
        ),
    ]
