# Generated by Django 5.1.2 on 2024-11-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playstyle_compass", "0046_gamelist_favorites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="favorite_games",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="game_queue",
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="favorite_games",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_by_users",
                to="playstyle_compass.game",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="game_queue",
            field=models.ManyToManyField(
                blank=True, related_name="queued_by_users", to="playstyle_compass.game"
            ),
        ),
    ]
