# Generated by Django 4.2.4 on 2023-12-21 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0047_alter_message_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="message",
            table="Message",
        ),
    ]
