# Generated by Django 4.2.4 on 2023-12-21 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstyle_compass", "0048_alter_message_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="game",
        ),
    ]
