# Generated by Django 4.2.4 on 2024-01-06 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_message_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="message",
        ),
    ]
