# Generated by Django 4.2.4 on 2024-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_rename_content_message_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(max_length=3500),
        ),
    ]
