# Generated by Django 4.2.4 on 2024-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_notification_created_at_notification_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
