# Generated by Django 4.2.4 on 2024-01-13 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_notification_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
