# Generated by Django 4.2.4 on 2024-01-13 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_rename_created_at_notification_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="timestamp",
        ),
    ]
