# Generated by Django 4.2.4 on 2024-01-14 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_notification_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
