# Generated by Django 4.2.4 on 2024-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_notification_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
