# Generated by Django 5.0.2 on 2024-03-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_userprofile_timezone_alter_message_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
