# Generated by Django 5.0.2 on 2024-03-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_userprofile_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
