# Generated by Django 5.0.2 on 2024-04-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_quizquestion_alter_message_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizuserresponse",
            name="option1",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="quizuserresponse",
            name="option2",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="quizuserresponse",
            name="option3",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="quizuserresponse",
            name="option4",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="quizuserresponse",
            name="response_text",
            field=models.CharField(default="", max_length=200),
        ),
    ]
