# Generated by Django 5.0.2 on 2024-04-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_remove_quizuserresponse_option1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="name",
            field=models.CharField(default="asd", max_length=100),
            preserve_default=False,
        ),
    ]
