# Generated by Django 5.0.2 on 2024-04-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_userprofile_quiz_taken_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
