# Generated by Django 5.0.2 on 2024-04-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_userprofile_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="option1",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="option2",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="option3",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="option4",
            field=models.CharField(default="", max_length=150),
        ),
    ]
