# Generated by Django 5.0.2 on 2024-05-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_friendlist_friends_alter_friendlist_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="option1_en",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="option1_ro",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="option2_en",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="option2_ro",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="option3_en",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="option3_ro",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="option4_en",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="option4_ro",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="question_text_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="question_text_ro",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
