# Generated by Django 5.0.2 on 2024-05-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_quizquestion_option1_en_quizquestion_option1_ro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizuserresponse",
            name="response_text_en",
            field=models.CharField(default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="quizuserresponse",
            name="response_text_ro",
            field=models.CharField(default="", max_length=200, null=True),
        ),
    ]
