# Generated by Django 5.0.2 on 2024-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_quizuserresponse_response_text_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="quiz_taken",
            field=models.BooleanField(default=False),
        ),
    ]
