# Generated by Django 5.0.2 on 2024-05-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_userprofile_quiz_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizuserresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
