# Generated by Django 5.0.2 on 2024-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_quizuserresponse_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(
                default="",
                help_text="A short bio, up to 160 characters.",
                max_length=160,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_character",
            field=models.CharField(
                default="",
                help_text="Your favorite game character, up to 100 characters.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_game",
            field=models.CharField(
                default="",
                help_text="Your favorite game, up to 100 characters.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="main_gaming_platform",
            field=models.CharField(
                choices=[
                    ("PC", "PC"),
                    ("PlayStation", "PlayStation"),
                    ("Xbox", "Xbox"),
                    ("Nintendo", "Nintendo"),
                    ("Mobile", "Mobile"),
                ],
                default="PC",
                help_text="Your main gaming platform.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_media",
            field=models.CharField(
                default="",
                help_text="The gamer's social media handle, up to 100 characters.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="type_of_gamer",
            field=models.CharField(
                choices=[
                    ("Casual", "Casual"),
                    ("Hardcore", "Hardcore"),
                    ("Professional", "Professional"),
                ],
                default="Casual",
                help_text="What type of gamer you are (e.g., casual, hardcore).",
                max_length=50,
            ),
        ),
    ]
