# Generated by Django 5.0.2 on 2024-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_userprofile_bio_userprofile_favorite_character_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="type_of_gamer",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gaming_commitment",
            field=models.CharField(
                default="Casual",
                help_text="Choose your level of commitment in gaming.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(
                default="",
                help_text="Write a short bio, up to 50 characters.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_character",
            field=models.CharField(
                default="",
                help_text="Enter your favorite game character, up to 50 characters.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_game",
            field=models.CharField(
                default="",
                help_text="Enter your favorite game, up to 50 characters.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="main_gaming_platform",
            field=models.CharField(
                default="PC",
                help_text="Choose your main gaming platform.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="social_media",
            field=models.CharField(
                default="",
                help_text="Enter your social media link",
                max_length=100,
                null=True,
            ),
        ),
    ]
