# Generated by Django 5.0.2 on 2024-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_remove_userprofile_type_of_gamer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gaming_genres",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gaming_setup",
            field=models.TextField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_character",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_game",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gaming_commitment",
            field=models.CharField(default="Casual", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="main_gaming_platform",
            field=models.CharField(default="PC", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="social_media",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
