# Generated by Django 5.0.2 on 2024-06-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_userprofile_favorite_franchise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="streaming_preferences",
            field=models.CharField(default="", max_length=50, null=True),
        ),
    ]
