# Generated by Django 5.0.2 on 2024-07-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="recipient_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
