# Generated by Django 5.0.2 on 2024-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_chatmessage_recipient_hidden_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_chat_notification",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
