# Generated by Django 5.0.2 on 2024-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_userprofile_last_chat_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
