# Generated by Django 5.0.2 on 2024-07-16 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_chatmessage_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
