# Generated by Django 5.0.2 on 2024-07-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_alter_chatmessage_creation_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="creation_time",
        ),
        migrations.RemoveField(
            model_name="chatmessage",
            name="updated_at",
        ),
    ]
