# Generated by Django 5.0.2 on 2024-07-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_remove_chatmessage_creation_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
