# Generated by Django 5.0.2 on 2024-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0051_userprofile_is_online_userprofile_last_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_online",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
