# Generated by Django 5.0.2 on 2024-08-09 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0052_alter_userprofile_last_online"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="blocked_users",
            field=models.ManyToManyField(
                related_name="blocked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
