# Generated by Django 5.0.2 on 2024-08-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0054_alter_userprofile_blocked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
