# Generated by Django 5.0.2 on 2024-08-16 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_chatmessage_pinned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="pinned",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
