# Generated by Django 5.0.2 on 2024-09-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0057_remove_chatmessage_pinned_chatmessage_pinned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_game",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_game_modes",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_soundtrack",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gaming_alias",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gaming_commitment",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="main_gaming_platform",
            field=models.CharField(default="", max_length=50),
        ),
    ]
