# Generated by Django 5.0.2 on 2024-09-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0058_userprofile_current_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gaming_commitment",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="main_gaming_platform",
            field=models.CharField(default="", max_length=50, null=True),
        ),
    ]
