# Generated by Django 5.1.2 on 2024-10-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0062_notification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receive_review_notifications", models.BooleanField(default=True)),
                ("receive_follow_notifications", models.BooleanField(default=True)),
                (
                    "receive_friend_request_notifications",
                    models.BooleanField(default=True),
                ),
                ("receive_message_notifications", models.BooleanField(default=True)),
                (
                    "receive_chat_message_notifications",
                    models.BooleanField(default=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
