# Generated by Django 5.1.2 on 2024-10-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0063_usernotificationpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_chat_message_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_follow_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_friend_request_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_message_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_review_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="UserNotificationPreferences",
        ),
    ]
