# Generated by Django 5.1.2 on 2024-10-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0065_notification_delivered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=200),
        ),
    ]
