# Generated by Django 5.1.2 on 2024-10-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0067_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receiver_shared_game_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="delivered",
            field=models.BooleanField(default=True),
        ),
    ]
