# Generated by Django 5.1.2 on 2024-10-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0069_userprofile_receive_shared_game_list_notifications_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="receiver_shared_game_notifications",
            new_name="receive_shared_game_notifications",
        ),
    ]
