# Generated by Django 5.1.2 on 2025-01-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0071_globalchatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message_translations",
            field=models.JSONField(default=dict),
        ),
    ]
