# Generated by Django 5.1.2 on 2025-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0072_notification_message_translations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message_translations",
        ),
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_ro",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(default=""),
        ),
    ]
