# Generated by Django 5.1.2 on 2025-01-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0073_remove_notification_message_translations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message_en",
        ),
    ]
