# Generated by Django 5.1.2 on 2025-01-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0074_remove_notification_message_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ro", "Romanian")],
                default="en",
                max_length=5,
            ),
        ),
    ]
