# Generated by Django 5.1.2 on 2025-02-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0075_userprofile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="api_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="api_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
