# Generated by Django 5.1.2 on 2025-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0076_userprofile_api_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="api_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
