# Generated by Django 5.1.2 on 2025-02-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0077_userprofile_api_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="api_access_token",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="api_refresh_token",
        ),
    ]
