# Generated by Django 5.1.2 on 2025-05-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0078_remove_userprofile_api_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_shared_deal_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("review", "Review"),
                    ("follow", "Follow"),
                    ("friend_request", "Friend Request"),
                    ("message", "Message"),
                    ("chat_message", "Chat Message"),
                    ("shared_game", "Shared Game"),
                    ("shared_game_list", "Shared Game List"),
                    ("shared_deal", "Shared Game Deal"),
                ],
                max_length=20,
            ),
        ),
    ]
