# Generated by Django 5.1.2 on 2026-01-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0080_userprofile_receive_shared_review_notifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="is_online",
        ),
        migrations.AlterField(
            model_name="quizuserresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
